---
apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: AvailabilityTarget
metadata:
  name: cdelashmutt-kind
  namespace: default
spec:
  affinity:
    clusterAffinity:
      clusterSelectorTerms:
      - matchExpressions:
        - key: tmc.cloud.vmware.com/creator
          operator: In
          values:
          - chris.delashmutt_broadcom.com
        - key: region
          operator: In
          values:
          - kind
    clusterAntiAffinity:
      clusterSelectorTerms: []