apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: api-portal
  namespace: sync
  annotations:
    kapp.k14s.io/change-group: pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgr"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgr"
    kapp.k14s.io/change-rule.2: "upsert after upserting sso-credentials"
    kapp.k14s.io/change-rule.3: "delete before deleting sso-credentials"
spec:
  serviceAccountName: install
  packageRef:
    refName: api-portal.tanzu.vmware.com
    versionSelection:
      constraints: ">=0.0.0"
  values:
    - secretRef:
        name: api-portal-values
