apiVersion: v1
kind: Secret
metadata:
  name: api-portal-values
  namespace: sync
type: Opaque
stringData:
  values.yaml: |
    sso:
      enabled: true
      secretName: sso-credentials
    apiKey:
      enabled: true
      vault:
        role: api-portal-role
        path: api-portal-keys
        url: http://vault.vault.svc:8200/
    apiPortalServer:
      title: API Portal
      description: API Portal for Chris DeLashmutt's Kind Cluster
      limitMemory: 1024Mi
      namespace: api-portal
      replicaCount: 1
      requestMemory: 512Mi
      sourceUrls: http://scg-openapi-service.spring-cloud-gateway.svc/openapi
      sourceUrlsTimeoutSec: "10"
      limitCpu: 500m
      requestCpu: 100m
      sourceUrlsCacheTtlSec: "300"