apiVersion: v1
kind: Secret
metadata:
  name: api-portal-values
  namespace: sync
type: Opaque
stringData:
  values.yaml: |
    sso:
      enabled: false
      secretName: sso-credentials
    apiKey:
      enabled: false
      vault:
        role:
        url:
    apiPortalServer:
      title: API Portal
      description: API Portal for <namespace> Namespace
      limitMemory: 1024Mi
      namespace: api-portal
      replicaCount: "1"
      requestMemory: 512Mi
      sourceUrls: https://petstore.swagger.io/v2/swagger.json,https://petstore3.swagger.io/api/v3/openapi.json
      sourceUrlsTimeoutSec: "10"
      limitCpu: 500m
      requestCpu: 100m
      sourceUrlsCacheTtlSec: "300"