apiVersion: v1
kind: Secret
metadata:
  name: sso-credentials
  namespace: api-portal
  annotations:
    kapp.k14s.io/change-group: sso-credentials
type: Opaque
stringData:
  sso-credentials.txt: |
    scope=openid,profile,email
    client-id={your_client_id}
    client-secret={your_client_secret}
    issuer-uri=https://console.tanzu.broadcom.com/csp/gateway/am/api/.well-known/openid-configuration