#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
    name: sso-credentials
    namespace: api-portal
type: Opaque
stringData:
  scope: openid,profile,email
  client-id: #@ data.values.apiPortal.sso.clientId
  client-secret: #@ data.values.apiPortal.sso.clientSecret
  issuer-uri: http://auth-server.kind.local
