apiVersion: v1
kind: Secret
metadata:
  name: remove-ns
type: Opaque
stringData:
  overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "Namespace", "metadata":{"name":"api-portal"}})
    #@overlay/remove
