#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
    name: sso-credentials
    namespace: api-portal
    annotations:
        kapp.k14s.io/change-group: sso-credentials
type: Opaque
stringData:
    #@yaml/text-templated-strings
    sso-credentials.txt: |-
        scope=openid,profile,email
        client-id=(@-= data.values.apiPortal.sso.clientId @)
        client-secret=(@-= data.values.apiPortal.sso.clientSecret @)
        issuer-uri=https://console.tanzu.broadcom.com/csp/gateway/am/api/.well-known/openid-configuration
