apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: vault
spec:
  syncPeriod: 1m
  serviceAccountName: install
  packageRef:
    refName: vault.se.tanzu.broadcom.com
    versionSelection:
      constraints: ">0.0.0"
